# Configuration file for the survey LSST
name: lsst
release: yr4
survey_files: 
    # Path to data files (leave empty for default location)
    file_path: ''

    # Band-specific magnitude limit maps
    maglim_map_g: baseline_v5.0.0_year_4.0_band_g_nside_128.hsp
    maglim_map_r: baseline_v5.0.0_year_4.0_band_r_nside_128.hsp

    # Band-independent maps
    ebv_map: ebv_sfd98_lowres_nside_512_ring_equatorial.fits
    completeness: stellar_efficiency_cutr.csv
    log_photo_error: photoerror_r.csv

survey_properties: 
  bands: ['u', 'g', 'r', 'i', 'z', 'y']

  # Extinction coefficients per band (A_band / E(B-V)) 
  # From rubin_sim (verions = 2.6.0, baseline version = 5.0.0)
  # from rubin_sim.phot_utils import DustValues
  # dust_values = DustValues()
  # print(dust_values.r_x)
  coeff_extinc_u: 4.757217815396922
  coeff_extinc_g: 3.6605664439892625
  coeff_extinc_r: 2.70136780871597
  coeff_extinc_i: 2.0536599130965882
  coeff_extinc_z: 1.5900964472616756
  coeff_extinc_y: 1.3077049588254708

  # Systematic photometric errors (mag), or could be specified as sys_error_g, sys_error_r, etc
  sys_error : 0.005 # Error common to all bands
  # sys_error_i: 0.01  # Example to Override for i-band


  # Saturation limits per band, or could be specified as saturation_g, saturation_r, etc
  saturation: 16.0
  #saturation_u: 15.0  # Override for u-band
