# Simple stream that is uniform in density, track, and width.

stream:
  nstars: 5.0e+3
   
  density:
    type: Uniform
    xmin: -9.0
    xmax: +9.0

  track:
    center:
      type: Constant
      value: 0.0
    spread:
      type: Constant
      value: 0.2
    sampler: Gaussian

  isochrone:
    name: Bressan2012
    survey: lsst
    age: 12.0
    z: 0.0006
    band_1 : g
    band_2 : r
    band_1_detection : True
  
  distance_modulus:
    center: 
      type: Line
      slope: 0.1
      intercept: 16.5
    spread:
      type: Constant
      value: 0.0001 
    sampler: Uniform
   
background:
  nstars : 1.0e+5

  density:
    type: Uniform
    xmin: -10.0
    xmax: +10.0

  track:
    center:
      type: Constant
      value: 0.0
    spread:
      type: Constant
      value: 4.0
    sampler: Uniform
